// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)

// import { application } from "./application"
// import AvatarController from "./avatar_controller"
// application.register("avatar", AvatarController)

import { Application } from "@hotwired/stimulus"
import AvatarController from "./avatar_controller"

window.Stimulus = Application.start()
Stimulus.register("avatar", AvatarController)

