default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "app010_board_app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "app010_board_app_test") %>

production:
  <<: *default
  database: <%= ENV["PGDATABASE"] %>
